# Generated by Django 4.1.1 on 2022-10-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
