# Generated by Django 4.1.1 on 2022-10-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0002_producto_imagen_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='usuario',
        ),
    ]
