# Generated by Django 4.1.1 on 2022-10-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0003_remove_servicio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=True),
        ),
    ]
