# Generated by Django 4.1 on 2022-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0004_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_corte',
            field=models.CharField(choices=[('corte', 'corte'), ('cejas', 'cejas'), ('barba', 'barba'), ('corte y cejas', 'corte y cejas'), ('corte y barba', 'corte y barba'), ('corte completo', 'corte completo')], default=True, max_length=250),
        ),
    ]
