# Generated by Django 4.1 on 2022-11-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0005_cita_tipo_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Date'),
        ),
    ]
