# Generated by Django 4.1 on 2022-11-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0007_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(choices=[('9:00 am', '9:30 am'), ('9:30 am', '10:00 am'), ('10:00 am', '10:30 am'), ('10:30 am', '11:00 am'), ('11:00 am', '11:30 am'), ('11:30 am', '12:00 am'), ('12:00 m', '12:30 pm'), ('12:30 pm', '1:00 pm'), ('1:00 pm', '1:30 pm'), ('1:30 pm', '2:00 pm'), ('2:00 pm', '2:30 pm'), ('2:30 pm', '3:00 pm'), ('3:00 pm', '3:30 pm'), ('3:30 pm', '4:00 pm'), ('4:00 pm', '4:30 pm'), ('4:30 pm', '5:00 pm'), ('5:00 pm', '5:30 pm'), ('5:30 pm', '6:00 pm'), ('6:00 pm', '6:30 pm'), ('6:30 pm', '7:00 pm')]),
        ),
    ]
