# Generated by Django 4.1 on 2022-11-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberApp', '0009_alter_cita_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, unique=True, verbose_name='hora'),
        ),
    ]
